# Generated by Django 2.2.5 on 2020-04-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='movie1',
            field=models.CharField(default='Avatar', max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='movie2',
            field=models.CharField(default='Spectre', max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='movie3',
            field=models.CharField(default='Johnny English Reborn', max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='movie4',
            field=models.CharField(default='Die Another Day', max_length=256),
        ),
    ]
