# Generated by Django 2.2.5 on 2020-04-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20200418_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='replacer',
            field=models.IntegerField(default=4),
        ),
    ]
